### ISSUE TITLE
introduce a go.work file to avoid the custom code path in the go.mod

### ISSUE THREAD

**Issue by gedw99** [hkontrol/hkapp#2]
Its hard to me to reliably build because you have a replace pointing to a custom code path in https://github.com/hkontrol/hkapp/blob/main/go.mod

```
replace github.com/hkontrol/hkontroller => /home/bobalus/build/hkontroller
```

maybe use a go.work approach ?

Here is a good example: 
https://github.com/nanobus/iota/blob/main/go/go.work

**Comment by shabunin** [comment]
Thanks for information. Done.
go.work stays on my local machine as it supposed to be.
